steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '--no-cache',
        '-t',
        '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/${_CLOUD_RUN_SERVICE}:$COMMIT_SHA',
        '.'
    ]
    id: Build

  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/${_CLOUD_RUN_SERVICE}:$COMMIT_SHA']
    id: Push

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'beta',
        'run',
        'deploy',
        '--allow-unauthenticated',
        '${_CLOUD_RUN_SERVICE}',
        '--image', '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_CLOUD_RUN_SERVICE:$COMMIT_SHA',
        '--region', '$_DEPLOY_REGION',
        '--platform', 'managed',
        '--memory', '256Mi',
        '--update-env-vars',
        '
          APP_ENV=${_APP_ENV},
          APP_DEBUG=${_APP_DEBUG},
          APP_NAME=${_APP_NAME},
          DB_CONNECTION=${_DB_CONNECTION},
          BUILD=${_BUILD},
          QUEUE_CONNECTION=${_QUEUE_CONNECTION},
          QUEUE_FAILED_DRIVER=${_QUEUE_FAILED_DRIVER},
          STACKKIT_CLOUD_TASKS_PROJECT=${_STACKKIT_CLOUD_TASKS_PROJECT},
          STACKKIT_CLOUD_TASKS_LOCATION=${_STACKKIT_CLOUD_TASKS_LOCATION},
          STACKKIT_CLOUD_TASKS_HANDLER=${_STACKKIT_CLOUD_TASKS_HANDLER},
          STACKKIT_CLOUD_TASKS_QUEUE=${_STACKKIT_CLOUD_TASKS_QUEUE},
          STACKKIT_CLOUD_TASKS_SERVICE_EMAIL=${_STACKKIT_CLOUD_TASKS_SERVICE_EMAIL}',
        '--update-secrets=
          APP_KEY=Laravel_Breeze_B_APP_KEY:1,
          DB_HOST=Laravel_Breeze_B_DB_host:2,
          DB_DATABASE=Laravel_Breeze_B_DB_database:1,
          DB_USERNAME=Laravel_Breeze_B_DB_username:1,
          DB_PASSWORD=Laravel_Breeze_B_DB_password:1,
          SENTRY_DSN=Laravel-Breeze-B-Sentry-DSN:1'
    ]
    id: Deploy
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/${_CLOUD_RUN_SERVICE}:$COMMIT_SHA'
options:
  substitution_option: 'ALLOW_LOOSE'
substitutions:
  _CLOUD_RUN_SERVICE: 'laravel-b'
  _PLATFORM: 'managed'
  _SERVICE_NAME: 'laravel-b'
  _LABELS: ''
  _TRIGGER_ID: ''
  _DEPLOY_REGION: 'europe-north1'
  _GCR_HOSTNAME: 'eu.gcr.io'
  _APP_ENV: 'production'
  _APP_DEBUG: 'false'
  _APP_NAME: 'fnl.one | Laravel Jetstream | Single build (B)'
  _DB_CONNECTION: 'pgsql'
  _BUILD: 'prod'
  _QUEUE_CONNECTION: 'cloudtasks'
  _QUEUE_FAILED_DRIVER: ''
  _STACKKIT_CLOUD_TASKS_PROJECT: 'fnl-one'
  _STACKKIT_CLOUD_TASKS_LOCATION: ''
  _STACKKIT_CLOUD_TASKS_HANDLER: ''
  _STACKKIT_CLOUD_TASKS_QUEUE: ''
  _STACKKIT_CLOUD_TASKS_SERVICE_EMAIL: ''

tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - laravel-b




