version: "3"
services:
  fnl-laravel-jetstream:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          BUILD: 'local'
          PORT: '80'
    container_name: fnl-laravel-jetstream
    ports:
      - 8098:80
    volumes:
      - .:/var/www/html
    depends_on:
      - fnl-laravel-jetstream-db
    environment:
      APP_DEBUG: 'true'
      APP_NAME: 'fnl.one | Laravel jetstream'
      APP_ENV: 'local'
      # Generate a new key and paste below
      APP_KEY: 'base64:OoBYmwIIal8E8oeiX0oxZEx5/4V0/ZOa5nwsIwpcqQk='
      LOG_LEVEL: 'debug'
      APP_URL: 'http://210.91.1.1'
      DB_CONNECTION: 'pgsql'
      DATABASE_URL: 'pgsql://postgres:docker@fnl-laravel-jetstream-db:5432/postgres'
      #SENTRY_DSN: ''
      #QUEUE_CONNECTION: ''
      #QUEUE_FAILED_DRIVER: ''
      #STACKKIT_CLOUD_TASKS_PROJECT: ''
      #STACKKIT_CLOUD_TASKS_LOCATION: ''
      #STACKKIT_CLOUD_TASKS_HANDLER: ''
      #STACKKIT_CLOUD_TASKS_QUEUE: ''
      #STACKKIT_CLOUD_TASKS_SERVICE_EMAIL: ''
      #GOOGLE_APPLICATION_CREDENTIALS: ''
    networks:
      fnl-laravel-jetstream:
        ipv4_address: 210.91.1.1

  fnl-laravel-jetstream-db:
    image: postgres:latest
    ports:
    - 2346:5432
    volumes:
      - fnl_laravel_jetstream_db_data:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: docker
    container_name: fnl-laravel-jetstream-db
    networks:
      fnl-laravel-jetstream:
        ipv4_address: 210.91.1.2

#  redis:
#    image: redis:alpine
#    command: redis-server --requirepass docker
#    ports:
#      - 8379:6379
#    volumes:
#      - $PWD/redis-data:/var/lib/redis
#    environment:
#      - REDIS_REPLICATION_MODE=master
#    networks:
#      fnl-laravel-jetstream:
#        ipv4_address: 210.91.1.3

volumes:
  fnl_laravel_jetstream_db_data: {}
networks:
  fnl-laravel-jetstream:
    ipam:
      driver: default
      config:
        - subnet: 210.91.0.0/16
